"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var UsuarioDTO_1 = require("./UsuarioDTO");
var CrearUsuario_1 = require("./CrearUsuario");
var crearUsuarioApi = new CrearUsuario_1.default();
var crearUsuarioConsola = new CrearUsuario_1.Consola();
var usuarioDto1 = new UsuarioDTO_1.UsuarioDTO("Juan", "Perez", "juanperez@email.com", "123456", "123456");
var mensajeCreadoApi = crearUsuarioApi.createUser(usuarioDto1);
console.log(mensajeCreadoApi);
var usuarioDto2 = new UsuarioDTO_1.UsuarioDTO("Maria", "Lopez", "marialopez@email.com", "password123", "password123");
var mensajeCreadoConsola = crearUsuarioConsola.createUser(usuarioDto2);
console.log(mensajeCreadoConsola);
